# name: Deploy
# "on":
#   push:
#     branches:
#       - main
#   workflow_dispatch: {}
# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - uses: actions/setup-node@v2
#         with:
#           node-version: 16
#           cache: yarn
#       - run: yarn install --frozen-lockfile
#       - uses: azure/login@v1
#         with:
#           creds: ${{ secrets.AZURE_CREDENTIALS }}
#       - name: Run Azure Functions Action
#         uses: Azure/functions-action@v1
#         id: fa
#         with:
#           app-name: nubot
#           package: .

name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch: {}
        
jobs:
  deploy:
    runs-on: ubuntu-latest
        
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
        
    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: nileuregistry.azurecr.io/nu-bot:production
        platforms: linux/amd64
        file: Dockerfile
